# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275d5b8fb680efbd5d6d7afead152957e643cff0884ef0c84386ef3f0a007c40918e7dc20993d488aa89f0eeb6b67780fd5dc43e75aa44ecd6da0f0d2aba1044

test:
  secret_key_base: 94263ba3f56ad7f42a612e57f77f84e8efcf37db6bc80187e229efbd3af76c5d0e4fdb6b58133b2e30c32a1ffbcb2788c7c2146aad1171823ccf7af12c7d8e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
